#!/usr/bin/env bash
# Brings up the local backend for the Palloma Duarte Arquitetura app:
#   1. Docker Engine (rootful daemon, started manually since there is no systemd)
#   2. The local Supabase stack (Postgres + PostgREST + Auth + Studio)
#   3. A confirmed admin user for the /admin panel
#   4. A generated .env.local pointing the Next.js app at the local stack
#
# Safe to run repeatedly: every step checks current state before acting.
set -euo pipefail

REPO_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/../.." && pwd)"
cd "$REPO_ROOT"

ADMIN_EMAIL="${ADMIN_EMAIL:-admin@pdarquitetura.com.br}"
ADMIN_PASSWORD="${ADMIN_PASSWORD:-admin123456}"

log() { printf '\n\033[1;34m[start-services]\033[0m %s\n' "$*"; }

# ---------------------------------------------------------------------------
# 1. Docker daemon
# ---------------------------------------------------------------------------
# This VM's root filesystem is already an overlay mount, so the default
# overlay2 storage driver cannot nest. fuse-overlayfs is the working fallback.
start_docker() {
  if docker info >/dev/null 2>&1; then
    log "Docker daemon already running."
    return
  fi
  log "Starting Docker daemon (fuse-overlayfs storage driver)..."
  sudo nohup dockerd --storage-driver=fuse-overlayfs >/tmp/dockerd.log 2>&1 &
  for _ in $(seq 1 30); do
    if sudo docker info >/dev/null 2>&1; then break; fi
    sleep 1
  done
  # Let the agent user talk to the socket without sudo.
  sudo chmod 666 /var/run/docker.sock 2>/dev/null || true
  if ! docker info >/dev/null 2>&1; then
    log "ERROR: Docker daemon failed to start. Tail of /tmp/dockerd.log:"
    tail -n 20 /tmp/dockerd.log || true
    exit 1
  fi
  log "Docker daemon is up."
}

# Same-bridge container-to-container traffic is dropped by the kernel bridge
# netfilter hooks in this nested VM. Disabling them lets the Supabase
# containers reach Postgres over the private docker network.
relax_bridge_netfilter() {
  sudo sysctl -w net.bridge.bridge-nf-call-iptables=0 >/dev/null 2>&1 || true
  sudo sysctl -w net.bridge.bridge-nf-call-ip6tables=0 >/dev/null 2>&1 || true
}

# ---------------------------------------------------------------------------
# 2. Supabase stack
# ---------------------------------------------------------------------------
start_supabase() {
  if supabase status >/dev/null 2>&1; then
    log "Supabase stack already running."
    return
  fi
  log "Starting local Supabase stack (this pulls images on first run)..."
  supabase start
}

# ---------------------------------------------------------------------------
# 3. Admin user (idempotent)
# ---------------------------------------------------------------------------
seed_admin_user() {
  log "Ensuring admin user ${ADMIN_EMAIL} exists..."
  local api_url service_key
  api_url="$(supabase status -o env 2>/dev/null | sed -n 's/^API_URL="\(.*\)"$/\1/p')"
  service_key="$(supabase status -o env 2>/dev/null | sed -n 's/^SERVICE_ROLE_KEY="\(.*\)"$/\1/p')"
  # Create the user; a 422 (already exists) is fine.
  curl -s -o /dev/null -X POST "${api_url}/auth/v1/admin/users" \
    -H "apikey: ${service_key}" \
    -H "Authorization: Bearer ${service_key}" \
    -H "Content-Type: application/json" \
    -d "{\"email\":\"${ADMIN_EMAIL}\",\"password\":\"${ADMIN_PASSWORD}\",\"email_confirm\":true}" || true
}

# ---------------------------------------------------------------------------
# 4. .env.local for the Next.js app
# ---------------------------------------------------------------------------
write_env_local() {
  log "Writing .env.local..."
  local api_url pub_key
  api_url="$(supabase status -o env 2>/dev/null | sed -n 's/^API_URL="\(.*\)"$/\1/p')"
  pub_key="$(supabase status -o env 2>/dev/null | sed -n 's/^PUBLISHABLE_KEY="\(.*\)"$/\1/p')"
  cat > .env.local <<EOF
# Auto-generated by .cursor/scripts/start-services.sh
# Local Supabase dev keys (published defaults — not secrets).
NEXT_PUBLIC_SUPABASE_URL=${api_url}
NEXT_PUBLIC_SUPABASE_PUBLISHABLE_KEY=${pub_key}
NEXT_PUBLIC_SITE_URL=http://localhost:3000
# Optional: set GEMINI_API_KEY to enable the AI blog-post generator.
${GEMINI_API_KEY:+GEMINI_API_KEY=$GEMINI_API_KEY}
EOF
}

start_docker
relax_bridge_netfilter
start_supabase
seed_admin_user
write_env_local

log "Backend ready."
log "  App:      http://localhost:3000"
log "  Supabase: $(supabase status -o env 2>/dev/null | sed -n 's/^STUDIO_URL="\(.*\)"$/\1/p') (Studio)"
log "  Admin:    ${ADMIN_EMAIL} / ${ADMIN_PASSWORD}"
